CREATE ROLE admin_kr WITH
    LOGIN
    NOSUPERUSER
    CREATEDB
    NOCREATEROLE
    INHERIT
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1
    PASSWORD '123456';

CREATE DATABASE krdb
	WITH
	OWNER=admin_kr
	ENCODING='UTF8'
	CONNECTION LIMIT=-1
	IS_TEMPLATE=False;