server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/krdb
    username: admin_kr
    password: 123456

email:
  recipient: ${MAIL_APP}
  password: ${MAIL_PASSWORD_APP}

app:
  jwt:
    secret: ${SECRET_KEY}
